### ISSUE TITLE
Switch images to use jdk11

### ISSUE THREAD

**Issue by fiidim** [spring-cloud/spring-cloud-skipper#1003]
I've always built and deployed SCDF apps using openjdk 11.0.8.  Prior to 2.7 the image my apps deployed ok.  After moving to 2.7 I now get:

```
java.lang.UnsupportedClassVersionError: <class> has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_282]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[na:1.8.0_282]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_282]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_282]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_282]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_282]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_282]
```

Not sure why the project went backwards a version, and I haven't found release notes on how to introduce newer runtimes.  Did I miss something?

Was:
```
[root@rhel76pr repository]# docker exec -it skipper /bin/bash
root@a1dca0b40e15:/# find . -name 'java'
./usr/lib/jvm/jre-11.0.8/bin/java
root@a1dca0b40e15:/# /usr/lib/jvm/jre-11.0.8/bin/java -version
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.8+10-LTS, mixed mode)
```

**Comment by jvalkeal** [comment]
Ah this was a mistake we/I made when moving image generation from maven plugin to paketo. scdf/skipper 2.6.x/2.5.x were on jdk8, scdf/skipper 2.7.x/2.6.x were on jdk11. I think we were supposed to be jdk8 even on 2.7.x as we were afraid to pump up but looks like we silently went on with jdk11.

Having said that, we can go back to jdk11 in next maintenance release.

Sorry for this, and thanks for reporting.

**Comment by fiidim** [comment]
Thanks for looking at this.  It's an interesting dilemma though.  If `skipper` itself needs a `1.8` runtime, but the `apps` that run in the `skipper` image need a higher minimum runtime, it almost seems that the `jre` or build image needs to have an option runtime version for the apps.

It looks like other people are/were doing the same thing.  This [issue](https://github.com/spring-cloud/spring-cloud-skipper/issues/988) talks about needing `14`, and this [issue](https://github.com/spring-cloud/spring-cloud-skipper/issues/971) reports a warning with `11`.

In the meantime, I will try out your new images and let me know.  When I did the upgrade I also hit an issue with `docker-compose.yml` and local maven repositories.  I'm not sure whether the latest `docker-compose.yml` file introduced something ahead of the build or not.  Definitely related to having `/home/cnb` vs `/root` for mounting the local repository.
