### ISSUE TITLE
align commands with those of helm

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#102]
remove the prefix 'package' in commands and align with helm nomenclature.

`package deploy -> install`
`package update -> upgrade`
`package rollback -> rollback`
`package undeploy -> delete`

unique to skipper
`package upload -> upload`

`repository add -> repo add` etc.

Also for the commands
`skipper info -> info`
`skipper config server -> config`

Delete `ReleaseCommands`

Merge `PackageController` and `ReleaseController` into `SkipperController`.

change `@RequestMapping(path = "/{id}/deploy"` to `@RequestMapping(path = "/deploy/{id}"`

**Comment by ilayaperumalg** [comment]
Addressed the changes and pushed into master a3b360f1ed773db72173f9ea9b54fbdb78f24817, 75a441000ddeaa9c3cc3e849c75f0d99ae6f833d, bd4729215118b0333b9a398c57929c6bd9f762da, 0ed8432c79a8329122990ff91e336def05e2a445, 3646d952fe67e798d70b4acec5ef9b9823073c40 and 5aa20997a4a5d7301086da061c4becb57312ab1d as individual changes to track them easily.
