### ISSUE TITLE
Make cloud skipper jar executable

### ISSUE THREAD

**Issue by ccanning** [spring-cloud/spring-cloud-skipper#1051]
This request is effectively the same as [#4941] (https://github.com/spring-cloud/spring-cloud-dataflow/issues/4941).

**Problem description**:

We need to run skipper local as a service. Shell already has the executable flag set to true in the spring boot maven plugin.

**Solution description**:

In your Maven build, add this to the spring boot maven plugin configuration:

<executable>true</executable>

so, it should look similar to this basic version:

<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <configuration>
        <executable>true</executable>
    </configuration>
</plugin>
Description of alternatives:
If using gradle, use:

springBoot {
    executable = true
}

This is also fine using a profile specific to local. 

Thanks.

**Comment by onobc** [comment]
Closing for the same reasons listed [here](https://github.com/spring-cloud/spring-cloud-dataflow/issues/4941#issuecomment-1168157723).
