### ISSUE TITLE
Add shell command to retrieve package summaries

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#12]
As a developer, I'd like to add a shell command to retrieve all the available packages.

**Notes:**
This command will invoke the `findAllPackageSummary` backend operation.

**Acceptance:** 
The new command (maybe: `skipper:>package list`?) retrieves all the packages.

**Comment by markpollack** [comment]
I agree, typing `skipper:>skipper list` isn't as clear as `package list`.
