### ISSUE TITLE
Expose repository name and package version when deploying using skipper

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#169]
May want to only have these options when using `stream deploy` and not `stream create` , otherwise the stream create command gets too many options related to deployment.

The hardcoded package version (1.0.0) and repository name (local) used when deploying at stream creating time can maybe used and make configurable for `stream create`

**Comment by ilayaperumalg** [comment]
I believe this is intended to be in SCDF and addressed via https://github.com/spring-cloud/spring-cloud-dataflow/pull/1693 and hence can be closed.
