### ISSUE TITLE
SkipperStreamDeployer state mapping when ReleseNotFoundException is thrown

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#173]
When creating a new stream and not calling `--deploy` but using `--useSkipper` a subsequent call to `stream status` will return a `ReleaseNotFoundException` from skipper. This can be fixed by catching this exception and setting the deployment state of the stream to unknown.  

Also, now that ReleaseNotFoundException is in the core shared project between skipper clients and server, we can remove 

```
	@ResponseStatus(value = HttpStatus.NOT_FOUND, reason = "Release doesn't exist")
	@ExceptionHandler(ReleaseNotFoundException.class)
	public void releaseNotExist() {
		// handle ReleaseNotFoundException by returning 404
	}```

in SkipperController.

**Comment by jvalkeal** [comment]
Well, client doesn't know anything about `ReleaseNotFoundException` as this exception is not propagated via rest layer. SkipperClient rely on getting 404 from server. Point was that at some point client could use same exceptions, possibly throwing something what it thinks server send via rest.

But I think I got what you meant. I'll try from scdf how this looks like.
