### ISSUE TITLE
Harmonise command options

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#174]
we have different argument names `name` vs. `package-name` and `version` vs. `package-version` in
```
skipper:>install --name log --version 1.0.0 --release-name mylog
skipper:>upgrade --release-name mylog --package-name log --package-version 2.0.0
```
should really make consistent use throughout all commands

**Comment by sabbyanandan** [comment]
The `install` and `upgrade` commands include `--package-name` as the property. `--name` is not listed anywhere anymore.
