### ISSUE TITLE
The README Quick Tour section on upgrading 'mylog' release references the wrong version of log-sink-rabbit

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-skipper#191]
Following the [Quick Tour](https://github.com/spring-cloud/spring-cloud-skipper#quick-tour) section, when upgrading the `mylog` release to version `2.0.0` of the `log` package:

```console
skipper:>upgrade --release-name mylog --package-name log --package-version 2.0.0
...
```

is supposed to deploy `log-sink-rabbit-1.2.0.RELEASE.jar`.

However, version `log-sink-rabbit-1.1.1.RELEASE.jar` is actually deployed:

``` console
skipper:>get manifest --release-name mylog

---
# Source: log.yml
apiVersion: skipper/v1
kind: SpringBootApp
metadata:
  name: log
  count: 1
  type: sink
spec:
  resource: maven://org.springframework.cloud.stream.app:log-sink-rabbit:1.1.1.RELEASE
  resourceMetadata: maven://org.springframework.cloud.stream.app:log-sink-rabbit:jar:metadata:1.1.1.RELEASE
  applicationProperties:
  deploymentProperties:
```

```console
$ watch jps
Every 2.0s: jps                                                                                                                                                                                                  Donovans-MacBook-Pro.local: Sun Oct 15 22:00:09 2017

87169 log-sink-rabbit-1.1.1.RELEASE.jar
86384 spring-cloud-skipper-server-1.0.0.BUILD-SNAPSHOT.jar
87191 Jps
86454 spring-cloud-skipper-shell-1.0.0.BUILD-SNAPSHOT.jar
81258 RemoteMavenServer
```

This is because of the version override in [`values.yml`](https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server/src/test/resources/repositories/sources/test/log/log-2.0.0/values.yml#L4) from `spring-cloud-skipper/spring-cloud-skipper-server/src/test/resources/repositories/binaries/test/log/log-2.0.0.zip`:

```yaml
# Default values for {{name}}
# This is a YAML-formatted file.
# Declare variables to be passed into your templates
version: 1.1.1.RELEASE
metadata:
  count: 1
```

**Comment by ilayaperumalg** [comment]
@donovanmuller Thank you for reporting this issue.

**Comment by sabbyanandan** [comment]
This is addressed via: https://github.com/spring-cloud/spring-cloud-skipper/commit/3f75c3e6322c55b9d13589fb966816847b5345ff.
