### ISSUE TITLE
Add Travis and CodeCov integration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#2]
As a developer, I'd like to add Travis CI and CodeCov integration for Skipper.

**Acceptance:**
- Use `sudo: required` for Travis builds similar to [SCDF](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/.travis.yml#L1)
- Travis CI integration automatically builds each PR
- Travis + CodeCov integration automatically measure test coverage for each PR

**Comment by ilayaperumalg** [comment]
[vanakkam.py.zip](https://github.com/spring-cloud/spring-cloud-skipper/files/2183929/vanakkam.py.zip)
[hello.py.zip](https://github.com/spring-cloud/spring-cloud-skipper/files/2183930/hello.py.zip)
