### ISSUE TITLE
Move Spring Data REST repositories under `/api/repositories` URL

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#201]
There will likely be small differences in conventions between SDRest repo 'restful` semantics and those of the SkipperController.

Putting all the generated REST resources under the `api/repositories` will help to keep the distinction clear between the main controller in skipper and those generated.

**Comment by ilayaperumalg** [comment]
SInce we already ported all the REST endpoints into `/api` , Isn't the `/repositories` already under `/api` ?

**Comment by ghillert** [comment]
Closing for now. Not easily possible: 

E.g. setting `spring.data.rest.base-path` will mess with the root url listing of links. Also, customizing the mappings using `@RepositoryRestResource` is also problematic, e.g.:

`@RepositoryRestResource(path="repositories/deployer")` is not supported:

https://stackoverflow.com/questions/30396953/how-to-customize-spring-data-rest-to-use-a-multi-segment-path-for-a-repository-r

**Comment by ilayaperumalg** [comment]
@ghillert not sure I understood the requirement of this PR. Could you help me understand by commenting what you about this one: https://github.com/spring-cloud/spring-cloud-skipper/issues/201#issuecomment-337043433 ?
