### ISSUE TITLE
Investigate need to provide Content-Type for certain REST calls

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-skipper#205]
Certain Rest Calls seem to require a Content-Type headers to be specified, e.g.:

**InstallDocumentation**
**UpgradeDocumentation**
**UploadDocumentation**

E.g.:

```
final MediaType contentType = new MediaType(MediaType.APPLICATION_JSON.getType(),
				MediaType.APPLICATION_JSON.getSubtype(), Charset.forName("utf8"));
...
.accept(MediaType.APPLICATION_JSON).contentType(contentType)
...
```

If not specifying the Content-Type, you may get a `java.lang.AssertionError: Status expected:<201> but was:<415>`

This task has 3 components:

* Investigate why the header must be specify for those 3 endpoints
* Remove header-settings from Tests that don't need it
* Document those header requirements more explicitly in the docs if they are truly needed

**Comment by sabbyanandan** [comment]
Stale issue; closing it.
