### ISSUE TITLE
Change `--property-string` to `--properties`

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#224]
_From @markpollack on October 19, 2017 15:11_

Feedback shows that folks are confused by this. There isn't a simple way to say it is flattened yml..

_Copied from original issue: spring-cloud/spring-cloud-dataflow#1702_

**Comment by ilayaperumalg** [comment]
I think we need to update the same for `install` command as well.

**Comment by ilayaperumalg** [comment]
Also, the `message` in `assertMutuallyExclusiveFileAndProperties` needs to be fixed.
