### ISSUE TITLE
Mask sensitive data from being logged 

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-skipper#229]
There are places (especially in exception handlers), we seem to log manifest information etc.,

Since this could be critical information not intended to be logged, we can remove and replace it with the appropriate error messages.

**Comment by cppwfs** [comment]
I did some poking around and found where we log at debug level the entire manifest for example:
https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/service/ReleaseService.java#L181 
-and-
https://github.com/spring-cloud/spring-cloud-skipper/blob/master/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/AppDeployerReleaseManager.java#L90
Do these need to be removed, or does the content need to be redacted.

**Comment by sabbyanandan** [comment]
Thanks for the research! The last we discussed it, we wanted it to be masked since it will be useful information to log from troubleshooting standpoint (while on debug-mode). 

@ilayaperumalg: Do you have any other thoughts to share?
