### ISSUE TITLE
Add check at startup/reconfiguration that the provided server URL can be contacted.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#23]

**Comment by ericbottard** [comment]
More generally, on application startup we should attempt a connection to the server, publishing a reconfiguration event, etc.

This should also be an opportunity to simplify the `Target` code (even getting rid of it I think)

**Comment by markpollack** [comment]
merged as 73371a1585204dae2ef714b68aa23a82403dd2d2
