### ISSUE TITLE
Improve properties -> YAML conversion in shell

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#236]
Also, reuse and take advantage of STS team's "properties -> yaml" generator code.

**Comment by markpollack** [comment]
This is the code extracted from STS https://github.com/aclement/properties-to-yaml

The issue we have ATM, is that we 'flatten out' the application and deployment properties but not the rest of the structure.  In any case, this code should prove to be useful.

**Comment by jvalkeal** [comment]
sts4 beta i.e. gives warning/error that direct assignment will be dropped.
```
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
```
![sts-props-to-yaml](https://user-images.githubusercontent.com/50398/34494398-46f30d7e-efe8-11e7-9b31-08888e9a116f.png)
![sts-props-to-yaml2](https://user-images.githubusercontent.com/50398/34494401-4941cb1a-efe8-11e7-8179-74e446dd2215.png)

for conversion not to drop anything we should use tricks like converting to:
```
log4j:
  appender.stdout: org.xxx
  appender.stdout.Target: System.out
```
which a generic converter utility cannot easily do. If you have parent as a key high enough, then you end up
```
log4j.appender.stdout: org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target: System.out
```

I'd prefer to use same conversion logic as what i.e. sts is using.
