### ISSUE TITLE
ReleaseStateUpdateService touches wrong releases

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#259]
There's two separate issues:
1. As `findLatestDeployedOrFailed` is used, old failed releases will get updated. We probably care last new failed release but older should be left alone.
2. As this update happens on a background, simultaneous install/update which changes release versions will cause update to happen against older version.

**Comment by sabbyanandan** [comment]
The project has evolved significantly since when this issue was created - closing it as invalid.
