### ISSUE TITLE
Poll remote repositories for packages and sync with Skipper's content

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#262]
Remote repositories are currently only synchronized with Skipper on server startup.  Create a scheduled method that will poll these servers to keep package contents in sync in the background.

Expose a property to control the polling frequency.

Add a `repo update --repo-name` command to force the updating of package metadata for an existing repo.

When adding a new remote repository, also sync it's metdata contents.

**Comment by AWeeks1** [comment]
Also on this when repo delete should remove the packages that it references.
(`repo --update *` would also do this).

**Comment by sabbyanandan** [comment]
The project has evolved significantly since when this issue was created - closing it as invalid.
