### ISSUE TITLE
Skipper Shell: Help command throws error on multi-part instructions ("repo list")

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#316]
Would be convenient for shell to recognize two word, as well one word, commands.

i.e. 
When using the command:
`Help repo list` 
Throws `too many arguments`

Have to use help repo\ add 
(or help --command <TAB> which autocompletes)

**Comment by markpollack** [comment]
```
server-unknown:>help repo list
java.lang.IllegalArgumentException: Too many arguments: the following could not be mapped to parameters: 'list'
Details of the error have been omitted. You can use the stacktrace command to print the full stacktrace.
server-unknown:>help repo\ list

```

**Comment by cah-andrewfitzgerald** [comment]
help 'repo list' works as well

**Comment by ericbottard** [comment]
Indeed, this is "normal" and won't be fixed until "infinite arity" commands are supported, at which point the `help` command could recognize `help a b c` as a request for `"a b c"`

**Comment by sabbyanandan** [comment]
√
