### ISSUE TITLE
Support multiple ApplicationSpec readers

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-skipper#318]
Creating this story to track the discussion [here](https://github.com/spring-cloud/spring-cloud-skipper/pull/313#discussion_r150047111)

In summary, we need a way to support reading the application spec based on the specified application `kind`.

**Comment by sabbyanandan** [comment]
@ilayaperumalg: Is this also addressed in spring-cloud/spring-cloud-skipper#313?

**Comment by ilayaperumalg** [comment]
@sabbyanandan Yes, this is included there. I wish I could submit these as separate PRs but unfortunately, all these changes have some dependencies :-)
