### ISSUE TITLE
Spring Shell: Interrupting a running command shouldn't shut down shell 

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#333]
### Currently

If you are typing a command and then interrupt the terminal it will reset the line and give you a fresh line to write input (which is awesome). But if you do it while a command is running it cancels the command but also shuts down the shell. 

It would be nice if interrupting while a command is running did the same as when you are mid-way through typing a command.

**Comment by ericbottard** [comment]
done
