### ISSUE TITLE
Upgrading a package should delete previous runnings ones (PCF)

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#334]
I am pretty sure I saw or heard of an issue on this previously, or maybe it's in the next release. If so, sorry! 

But currently when you upgrade a package to push to PCF it does not take down the previous packages this has to be done manually. It would be nice if, when the new packages are up and running, the previous versions of the same package were deleted or stopped on PCF.

**Comment by sabbyanandan** [comment]
If the Skipper has the state intact, upon a upgrade to an existing package, the old package _will be_ taken down once after the successful instantiation and health-status of the new version.

This is in `master` and subsequently, it will result in the 1.0 M2 release. Please give it a go - if you still see issues in the local build / 1.0 BUILD-SNAPSHOT, we could have a look.

**Comment by sabbyanandan** [comment]
The project has evolved significantly since when this issue was created - closing it as invalid.
