### ISSUE TITLE
Packages which fail to deploy should stop themselves

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#335]
I am not sure if this is possible, but it might be? 

When I push to PCF, sometimes there is a build error and the app crashes. Currently PCF just keeps restarting them. It would be nice if they crash and the container is not healthy then it should stop it to prevent taking up resources (and in this case not take down previous builds).

**Comment by sabbyanandan** [comment]
What happens to the containers is outside of the cf-deployer and/or skipper's control. We don't keep any instrumentation on how many times the app-restart should be attempted and what to do if it never succeeds - we simply instead delegate that to the respective platform and mimic its runtime status.

I'm going to close this for now, but if there are other cases that you'd like for us to consider, do let us know.
