### ISSUE TITLE
Packages: Would be nice if you configure multiple values for different environments/spaces

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#336]
In PCF you can prepare a manifest.sb.yml, manifest.{{env}}.yml, etc. 

Currently, as a developer if I want to prepare custom, slightly different properties for different environment I have to change the values.yml file, re-zip the file and save it somewhere for each environment. 

It would be nice if packages mirrored this behavior, so when I write a package it would be nice to be able to set up a:
`values.sb.yml`, `values.sa.yml` or something and include them all in the same package and depending on the PCF space I deploy to it configures to the correct values file. (Either PCF space, or run-time configuration through a new flag like --file) in order to mirror PCF and avoid developers having to have 10 zip files with nearly identical contents with only small configuration changes.

**Comment by markpollack** [comment]
I thought that having one default `values.yml` and taking into account different environment by overriding the data in the `values.yml` file at deploy time would provide the necessary means to do this.  There isn't a need to have 10 .zip files.  For example. you can do

```
install --release-name helloworldpcf --package-name helloworld --platform-name cf-dev --file /home/mpollack/helloworld-dev.yml
```

for the dev org/space and 

```
install --release-name helloworldpcf --package-name helloworld --platform-name cf-qa1 --file /home/mpollack/helloworld-qa1.yml

```
for the qa org/space.

Thoughts? 

Also, have you considered using Config Server - as that is exactly the type of functionality provided for property management.

**Comment by sabbyanandan** [comment]
There's now support for "n" number of platform definitions. With that, one can define DEV, QA and among other platform accounts, so they can optionally deploy packages pointing to the desired org+space/namespace.
