### ISSUE TITLE
Bug: Skipper Shell unable to current status of upgraded package

### ISSUE THREAD

**Issue by AWeeks1** [spring-cloud/spring-cloud-skipper#341]
Update: Replicated.

### When 
I install a package (either custom and default given helloworld) and push it to PCF. 
### AND
I upgrade the package, using the upgrade command to another working version of the same package
### AND
I run the `status` or `history` command
### THEN
I receive the following status: 
For custom and default app:

![screen shot 2017-11-17 at 12 28 12 pm](https://user-images.githubusercontent.com/29645530/32967484-a3533d3e-cb92-11e7-8a68-1ad7a8588a83.png)

If I do a history on the app with multiple history I get this:

![screen shot 2017-11-17 at 12 14 34 pm](https://user-images.githubusercontent.com/29645530/32967041-f430e3c0-cb90-11e7-9f38-a1c5a2848046.png)

### Notes: 
The apps deploy successfully on PCF and can be found, **but** the old versions of the app are not deleted.

**Comment by ilayaperumalg** [comment]
@AWeeks1 Sorry about the delay on this. Could you confirm if this is only on PCF or does it happen on other platforms as well? Also, can you replicate this issue on local as well?

**Comment by ilayaperumalg** [comment]
Closing this for now.  Please feel free to re-open if you still see the issue.
