### ISSUE TITLE
Rename "uri" to "serverUri" in SkipperClientProperties

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#368]
The `host` property should just be the hostname.  Now it also includes `/api`, eg. `http://localhost:8080/api`. 

Perhaps the correct fix is to introduce a new property named `skipper.client.uri`.

Also, should we have the `spring.cloud` prefix as well?

**Comment by ilayaperumalg** [comment]
Not sure why do we want to call this as `skipper.client.uri` instead of `skipper.server.uri` 

+1 for having `spring.cloud.skipper.server.uri`

**Comment by markpollack** [comment]
The class has this prefix

```
@ConfigurationProperties("spring.cloud.skipper.client")
public class SkipperClientProperties {
```

@ilayaperumalg  I think we had mentioned to change the property name from just `uri` to `serverUri` ?

**Comment by ilayaperumalg** [comment]
yes, from `uri` to `serverUri`
