### ISSUE TITLE
Add multi-platform support

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#37]
Create @ConfigurationProperties classes per platform that provide necessary connection infomation.  Can model based on the approach used in config server for git/vault.

Each entry will have a name and will result in the creation of an AppDeployer instance for the relevant platform.

**Comment by ilayaperumalg** [comment]
Pushed the CF deployer support https://github.com/spring-cloud/spring-cloud-skipper/commit/947a12e2e2f3e9311d212a6ed66893cd4aeead5b

**Comment by ilayaperumalg** [comment]
Pushed the original changes via https://github.com/spring-cloud/spring-cloud-skipper/commit/1fd75bba4c6ca5566170ecbaeda7aef7c35afc1f
