### ISSUE TITLE
When shell is executed in non-interactive mode, any exception during shell command execution should return a non-zero exit code

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#372]
A variation on `ExitCodeExceptionMapper` maybe useful.  Commands can return string values that contain error messages and not a stack trace.

**Comment by jvalkeal** [comment]
This turned out to be impossible to implement from our side. It all boils down how shell core handles exceptions and you can't hack into shell core without breaking interactive features. Looks like we need to make shell core aware of more non-interactive features.

**Comment by markpollack** [comment]
Waiting on resolution of https://github.com/spring-projects/spring-shell/pull/189
