### ISSUE TITLE
Prepare tooling for DB schema changes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#382]
As a developer, I'd want to prepare tooling for future DB / schema changes (we will have to provide an option to not rely on auto-DDL always).

See also: https://github.com/spring-cloud/spring-cloud-dataflow/issues/1877

**Comment by ghillert** [comment]
created https://github.com/spring-cloud/spring-cloud-skipper/issues/395

**Comment by ghillert** [comment]
created https://github.com/spring-projects/spring-statemachine/issues/468
