### ISSUE TITLE
Refactor ReleaseAnalyzer to keep data structure with differences between releases.

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#384]
The current implementation builds a String that indicates there is a difference between one release an another.   There should instead be a simple boolean check based on the results of storing the different MapDifference instances and a new method created to "pretty print" what has changed.  This may also tie into the general 'show a diff' between two versions, though often the diff needs to be down in a pretty print style as well as a more version-control diff style (think git patches)

**Comment by markpollack** [comment]
The current implementation fails fast, so if there are differences in application properties, it doesn't bother to compute any differences in deployment properties.  The return value of the ReleaseDifference should include all the changes between two releases.
