### ISSUE TITLE
Provide a more complete description of each platform similar to RuntimeEnvironmentInfo in SCDF

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-skipper#392]
This is a requirement for the SCDF integration. 
SCDF's AboutController#getAboutResource requires the environmentInfo.

**Comment by tzolov** [comment]
When resolved, fix also the SCDF's SkipperStreamDeployer#environmentInfo()

**Comment by markpollack** [comment]
For now SCDF can return information about the skipper server version and the platform names it supports.

**Comment by sabbyanandan** [comment]
We now support multiple platform accounts, and they can be sufficiently descriptive given the deployer-sepcific configurations.
