### ISSUE TITLE
Fix sequence-based id generator deprecation warnings

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-skipper#395]
Setting `spring.jpa.properties.hibernate.id.new_generator_mappings=true` will remove 10 deprecation warnings in the logs:

```
HHH90000014: Found use of deprecated [org.hibernate.id.SequenceGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.
2018-01-04 11:30:45.513  WARN 53226 --- [  restartedMain] org.hibernate.orm.deprecation            : 
```

see https://stackoverflow.com/questions/39861098/replace-sequencegenerator-since-its-deprecated

see https://github.com/spring-projects/spring-boot/issues/7612

**Comment by ghillert** [comment]
Just FYI - when moving to Boot `2.0` eventually, property `spring.jpa.properties.hibernate.id.new_generator_mappings` can be removed.

**Comment by jvalkeal** [comment]
merged per https://github.com/spring-cloud/spring-cloud-skipper/commit/86835ccf8de8528b3de980183fafdf760201661b

**Comment by jvalkeal** [comment]
closed wrong one
