### ISSUE TITLE
Lock down Hibernate Dialect versions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#398]
As per the research, it looks like right now we rely on Spring Boot magic to select the right Hibernate Dialect. However, there are a plethora of [dialects](https://github.com/hibernate/hibernate-orm/tree/master/hibernate-core/src/main/java/org/hibernate/dialect) for different versions. Some of those choices may impact the underlying DB behavior - particularly MySQL. 

Thus, we should probably lock that down a bit (versions) and also document how users can customize to re-generate the SQL files for alternative versions.

spring-cloud/spring-cloud-skipper#382 uses the following dialects to generate the SQL schemas:

- H2Dialect
- HSQLDialect
- MySQL57Dialect
- Oracle10gDialect
- PostgreSQL95Dialect
- DB2Dialect
- SQLServer2012Dialect

**Comment by jvalkeal** [comment]
Right, this might explain why fully managed jpa with mysql works but script generated from tests is different and doesn't work.

**Comment by markpollack** [comment]
Related to https://github.com/spring-cloud/spring-cloud-skipper/issues/415

**Comment by sabbyanandan** [comment]
The project has evolved significantly since when this issue was created - closing it as invalid.
