### ISSUE TITLE
Remove generate-ddl:true from application.yml

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#433]
Test that sql scripts are loading against h2 and mysql.

**Comment by cppwfs** [comment]
I just ran a test where I renamed the postgresql94.sql to just postgresql.sql and boot used the correct sql file.  (Once I added the sql files to the resources).  I'll create a PR adding the sql files to the resources.

**Comment by sabbyanandan** [comment]
So, once #467 is merged, we don't have to mess with `spring.datasource.platform` property then? 

If yes, the scope of this story simply the removal of the "generate-ddl" property.
