### ISSUE TITLE
ReleaseRepository findLastDeployerOrFailed methods do not filter on latest release

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#441]
The query is implemented without any concept of 'last', just based on filtering findAll queries.  

This may not be a big since they are used in the list command command

```
	public List<Release> list(String releaseNameLike) {
		return this.releaseRepository.findLatestDeployedOrFailed(releaseNameLike);
	}
```

and querying over all deployed/failed apps to get release status, see `ReleaseStateUpdateService`

Maybe simply rename the method and change the docs for the `list` command.

**Comment by sabbyanandan** [comment]
Stale issue; closing it.
