### ISSUE TITLE
RESTDocs for RepositoryRepository.findByName

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#454]

**Comment by tzolov** [comment]
It looks like this issue has already been resolved: https://docs.spring.io/spring-cloud-skipper/docs/1.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#_find_by_name

Is there something else that needs to be done?

**Comment by sabbyanandan** [comment]
This is already addressed.
