### ISSUE TITLE
Prepare schemas for the release

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#461]
Review the schemas and prepare them with the "alter if not exist" / "create if not exist" clauses.

- [ ] MySQL - Vinny
- [ ] H2 - Vinny
- [ ] Db2 - Vinny
- [ ] HSQL - Vinny
- [ ] Postgres - Vinny
- [ ] SQLServer - Vinny 
- [ ] Oracle - Vinny

**Acceptance:**
Start the server; run a sample upload/install; restart the server; verify the table and the data remain undisturbed.

**Comment by sabbyanandan** [comment]
Get rid of all the drops and replace it with "create if not exist".

**Comment by sabbyanandan** [comment]
Delete "insert into hibernate_sequence values ( 1 );" entries.

**Comment by sabbyanandan** [comment]
Move all the alter table commands towards the bottom.

**Comment by cppwfs** [comment]
will need to merge https://github.com/spring-cloud/spring-cloud-skipper/pull/467 first, before working on this.
