### ISSUE TITLE
Polish DB schema

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#481]
1) We've changed all generated keys for skipper tables but one remains:
1.1) This will be addressed by adding `@JoinColumn(name = "packagefile_id", foreignKey = @ForeignKey(name = "fk_package_metadata_pfile"))` in `PackageMetadata`.
```
    alter table skipper_package_metadata·
        add constraint FKq2maocius5sr76isk7xlhn7b4·
        foreign key (packagefile_id)·
        references skipper_package_file;
```

2) Remove old schemas from [here](https://github.com/spring-cloud/spring-cloud-skipper/tree/master/spring-cloud-skipper-server-core/src/main/resources/db-schema).

3) Re-generate fresh schemas.

4) Verify the schemas load successfully.

**Comment by viniciusccarvalho** [comment]
@jvalkeal I think this may not be needed anymore, mostly only table names were causing issues with Oracle's 30 char limit.

**Comment by sabbyanandan** [comment]
All the remaining "constraint" statements have meaningful names as opposed to "FKq2maocius5sr76isk7xlhn7b4" in this case, so it can still be cleaned up.

**Comment by jvalkeal** [comment]
yeah,  gunnar pointed these out and we've fixed other except this.

**Comment by sabbyanandan** [comment]
Mark already merged it in https://github.com/spring-cloud/spring-cloud-skipper/commit/ea42716cc89a9b34af828c217d82f2f4075c2f47.
