### ISSUE TITLE
Improve status message when rolling back

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#500]
Not sure why it says the status is `UNKNOWN` when rolling back in the getting started sample when the platform status shows `initial install underway`.  

```skipper:>release rollback --release-name helloworldpcf --release-version 2
helloworldpcf has been rolled back.  Now at version v4.
skipper:>release history --release-name helloworldpcf
╔═══════╤════════════════════════════╤════════╤════════════╤═══════════════╤════════════════════════╗
║Version│        Last updated        │ Status │Package Name│Package Version│      Description       ║
╠═══════╪════════════════════════════╪════════╪════════════╪═══════════════╪════════════════════════╣
║4      │Thu Jan 18 13:51:43 EST 2018│UNKNOWN │helloworld  │1.0.0          │Initial install underway║
║3      │Thu Jan 18 13:49:42 EST 2018│DEPLOYED│helloworld  │1.0.1          │Upgrade complete        ║
║2      │Thu Jan 18 13:26:50 EST 2018│DELETED │helloworld  │1.0.0          │Delete complete         ║
║1      │Thu Jan 18 13:18:44 EST 2018│DELETED │helloworld  │1.0.0          │Delete complete         ║
╚═══════╧════════════════════════════╧════════╧════════════╧═══════════════╧════════════════════════╝
```

**Comment by jvalkeal** [comment]
I believe this is because it's UNKNOWN as that's what repository has. Status is mapped to StatusCode and it's not overridden in every call(like we do for platform status). When background task updates it, it becomes visible to shell.

**Comment by jvalkeal** [comment]
hold on, it doesn't get updated until we reach `org.springframework.cloud.skipper.server.deployer.strategies.HandleHealthCheckStep.updateReplacingReleaseState(Release)`. 

What comes for a StatusCode, there's nothing between UNKNOWN and DEPLOYED so it stays UNKNOWN until it either succeed or fails.
