### ISSUE TITLE
Review code to add @NotNullApi package annotation and @Nullable

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#54]
Encountered a few NPE's that would have been caught if we used these annotations.  For example, org.springframework.cloud.skipper.domain.Deploymnet had a null deploymentProperties value. we can set the field to an empty map.  Similarly,  the custom finder methods in ReleaseRepositoryImpl can return null.

See Spring 5 custom meta annotation.

**Comment by sabbyanandan** [comment]
The project has evolved significantly since when this issue was created - closing it as invalid.
