### ISSUE TITLE
Investigate CF Manifest integration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#568]
Add ability to manage any application that can be pushed into CF via Skipper. Primarily, this spike focuses on CF manifest based deployment.

**Comment by ilayaperumalg** [comment]
As part of this spike, the following changes are made:

1) Ability to read CF manifest based Skipper package in PackageReader
2) A new Release Manager to perform install/upgrade/rollback/delete
3) A new Manifest reader that delegates to the CF release manager
4) Ability to compute differences during upgrade in ReleaseAnalyzer
5) Provide configuration options for upgrade scenario
4) Shell command changes

The changes are pushed into this branch: https://github.com/ilayaperumalg/spring-cloud-skipper/tree/cf-manifest-support
