### ISSUE TITLE
Change rollback api to use domain object

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#601]
With install we use `InstallRequest` and with upgrade we use `UpgradeRequest` which allows to extend stuff passed in, i.e. for timeout field.

Rollback simply uses uri parameters to pass in `releaseName` and `releaseVersion` which doesn't work in a long run when we need to pass in more options. Should replace api with `RollbackRequest`.

child of #597

**Comment by ilayaperumalg** [comment]
We initially had `RollbackRequest` and switched back to these parameters as it fit better for the requirements we have now. I guess this was bound to change to a specific domain object as we get more options to it. Maybe this is the time ;) 

Btw, what specific options you are thinking of now?

**Comment by jvalkeal** [comment]
Options for timeout which relates to #587 as currently rollback can internally do an upgrade.
