### ISSUE TITLE
Upgrade to Spring Boot 1.5.13

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#617]
A few security fixes and dependency upgrades in this release; hopefully a straightforward upgrade.

**Comment by markpollack** [comment]
the CVEs don't impact us, so don't necessarily have to do this 'asap'

**Comment by jvalkeal** [comment]
Looks like we don't have `spring-cloud-build` which uses boot `1.5.13`. Not sure why.

**Comment by jvalkeal** [comment]
till then, removing from 1.0.5

**Comment by sabbyanandan** [comment]
This is not required anymore.
