### ISSUE TITLE
Remove SkipperManifestKind

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-skipper#628]
We don't want to have hard coded values as we only care about kind as string which we can use to check existing release managers.

child of #627

**Comment by ilayaperumalg** [comment]
After some investigation and changes, it would probably make sense to have Enum for checking the supported kinds as it is now being used in the release manager, upgrade strategy and the manifest reader. 

Pushed my WIP on this here: https://github.com/ilayaperumalg/spring-cloud-skipper/commit/8930d1c104aaf319e763d363e6ede8b2582da59f

**Comment by jvalkeal** [comment]
Not really sure if we need to do anything anymore. Enum is still there but it's just referenced from all `getSupportedKinds`  methods as Strings. This was all done in a last big refactoring.
