### ISSUE TITLE
Add Skipper-cli

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#7]
As a developer, I'd like to add the initial infrastructure for Skipper-cli, so we can use it to interact with the Skipper-server.

Depends on spring-cloud/spring-cloud-skipper#6.

**Acceptance:**
- Decide the default <PORT> to connect to Skipper-server.

**Comment by ericbottard** [comment]
Unless there is a good reason not to, this would be a good opportunity to test-drive [Spring Shell 2](https://github.com/ericbottard/spring-shell2)

**Comment by sabbyanandan** [comment]
@ericbottard: Depends on when 2.0 is planned to go GA. The initial MVP of Skipper is planned to go with SCDF 1.3 timeline.
