### ISSUE TITLE
Add a "--force" option for package upgrades

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#714]
As a user, I'd like to have a `--force` option for `skipper upgrade` command, so I can force upgrade the package even if there's no metadata change associated with it.

Notes:
This is a continuation from spring-cloud/spring-cloud-skipper#700. The idea is to allow upgrades for scenarios that involve config-server, where Skipper wouldn't be able to have direct access to query and react to external updates. The `--force` option would provide the ability to upgrade the package; likewise, the App would get rolling-upgraded, to bootstrap with the latest config-server changes.

**Comment by ilayaperumalg** [comment]
When doing the upgrade/rollback, we detect **only** those apps that have differences from the existing versions. With the `force` option, it may not be possible to find specific apps to upgrade/rollback instead of all the apps in the package would get re-deployed. I believe this adheres to our requirement.

**Comment by ilayaperumalg** [comment]
There are some caveats with the possible approaches to fixes this:


1) If we choose to use the `upgrade` flow to re-deploy the package:

  - the upgrade has to be on all the applications in the package (as mentioned in the above comment)
  - the way we check the health of the upgraded app and delete the existing one, we can't have the same name for both the apps (given we don't increment the version)

2) If we choose to use the `install` flow:
  - the existing release should be deleted first and then the new one should be installed with the same version which apparently misses our check on upgrade - deploy - verify - delete

We can possibly choose to have a different `name` and then change it back to `original` name after we find it to be healthy but that has other consequences come out of `name` specific dependencies (such as release name, routing etc.,)
