### ISSUE TITLE
Add integration tests infrastructure

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-skipper#75]
Add integration tests infrastructure to run end-to-end tests and could be very useful for the shell command tests as well.

**Comment by ericbottard** [comment]
See https://github.com/spring-projects/spring-shell/commit/8fd4d69a613b483bdbe6824983cb8d79bd42ca32

**Comment by sabbyanandan** [comment]
We run SACDF + Skipper ATs across many platforms and versions, so we don't need yet another infrastructure to run Skipper tests standalone.
