### ISSUE TITLE
Upgrade spring-cloud-services-dependencies to boot 2.1

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-skipper#750]
Skipper import `spring-cloud-services` (https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-dependencies-parent/pom.xml) for interacting with CF.
Later though is still at Boot 2.0.x

**Comment by sabbyanandan** [comment]
This required https://github.com/pivotal-cf/spring-cloud-services-starters/issues/57.

**Comment by sabbyanandan** [comment]
Closing this in favor of #784 and #785.
