### ISSUE TITLE
Make sure server starts if no internet connection

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#762]
From the logs

Downloading package metadata from URL [http://skipper-repository.cfapps.io/repository/experimental/index.yml]

In PCF environments outside internet access maybe disabled.  The server should start in anycase even if it can't fine a configured remote package repository.

**Comment by sabbyanandan** [comment]
We will add a new property (maybe: `SPRING_CLOUD_SKIPPER_SERVER_ENABLE_EXPERIMENTAL_REPOSITORY`), and by default, we will have it disabled. 

The tile experience would turn-it-off as well, so no-internet installs won't have the issue of downloading the experimental repository.

**Comment by jvalkeal** [comment]
Btw, we already have `--spring.cloud.skipper.server.synchonize-index-on-context-refresh=false` which doesn't prevent experimental repo to get added but it skips the sync stage and doesn't cause downloads.

**Comment by jvalkeal** [comment]
I was thinking to do a bit more polishing together with #788 by changing `Repository` in `SkipperServerProperties` be a real properties class as we should not use entity class there. Then It's easy and clear to add `enabled` flags to those properties per repo(thought sucks that repos is a list and not map.

**Comment by sabbyanandan** [comment]
Based on the discussion, we will remove experimental repo from skipper. No need of extra property. We will also update the ref. guide with instructions on how to add it if someone needs it.
