### ISSUE TITLE
Skipper Shell does not start

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#763]
$ java -jar ./spring-cloud-skipper-shell-2.0.0.BUILD-SNAPSHOT.jar 
ERROR: org.springframework.boot.SpringApplication : Application run failed
java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)

**Comment by sabbyanandan** [comment]
This is addressed in https://github.com/spring-cloud/spring-cloud-skipper/commit/0cfa9b22cb5e17190f38b54cea0990a517b378b0.
