### ISSUE TITLE
Revisit usage of spring.config.location

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-skipper#771]
In our docs we document using `--spring.config.location=skipper.yml` to provide additional configuration to Skipper.

However, that is not working - according to Boot docs it will *replace* the yml. In our case the application will most likely fail to start (even with a completely empty yaml file)

Instead it looks like we should be using `--spring.config.additional-location=skipper.yml`

**Comment by jvalkeal** [comment]
@sabbyanandan looks like I fixed these some time ago per d7f9baf615bc801b7e4cb38e77421653d0848cc0
