### ISSUE TITLE
Remove database connector dependency from the classpath

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#784]
As a developer, I'd like to remove the dependency of spring-cloud-connectors from the classpath; instead, we would switch to Boot's autoconfiguration proper.

**Comment by sabbyanandan** [comment]
This and spring-cloud/spring-cloud-dataflow#2724 needs to be a coordinated effort.

**Comment by markpollack** [comment]
Acceptance tests for CF will need to have

```
    SPRING_PROFILES_ACTIVE: cloud
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}
```

added.
