### ISSUE TITLE
Auto-detect whether or not the deployed platform is Kubernetes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#796]
Prior to starting the Skipper server, we would want to determine if we are Kubernetes. If we are not, we will have to set `spring.cloud.kubernetes.enabled` to "false".

**Comment by markpollack** [comment]
work done in https://github.com/spring-cloud/spring-cloud-dataflow/commit/7b0cb2ec4f10c0be2fb6b1fade9e1250def0e157  can help with this.
