### ISSUE TITLE
Reproduce the DB lock when using MySQL

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-skipper#797]
While on a multi-tenant PCF environment, we have a report of someone running into `(conn:129378) Lock wait timeout exceeded; try restarting transaction` error when deploying a stream using Skipper with MySQL (`dm-small` plan on pcf).

More details in slack [here](https://pivotal.slack.com/archives/G49UPQAP8/p1543964382133700).

Let's attempt to reproduce the reported behavior.

**Comment by ilayaperumalg** [comment]
Tried to deploy streams on this environment and I don't see any issues.
The MYSQL used were:
```
name            service      plan        bound apps   last operation
mysql           p.mysql      db-small                 create succeeded
mysql_skipper   p.mysql      db-small                 create succeeded
```

This is verified against the latest 2.0.0.BUILD-SNAPSHOT. Please re-open if this happens again.

Closing this for now.
