### ISSUE TITLE
dockerhub page should have a description

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#810]
ATM it is empty, should link to the project page.

**Comment by sabbyanandan** [comment]
See [SCDF-description](https://hub.docker.com/r/springcloud/spring-cloud-dataflow-server) for reference.

**Comment by chrisjs** [comment]
updated description with contents from cloud.spring.io - https://hub.docker.com/r/springcloud/spring-cloud-skipper-server
