### ISSUE TITLE
Review error handling in Shell 2.0 code.

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-skipper#84]
Do we need to do try/catch like this.

```
	@ShellMethod(key = "repository delete", value = "Delete a package repository")
	public String delete(@ShellOption(help = "name of the repository to delete") @NotNull String name) {
		try {
			this.skipperClient.deleteRepository(name);
			return "Repository " + name + " deleted.";
		}
		catch (Exception e) {
			return e.getMessage();
		}
	}```

or can we rely on the shell to catch the exception with the new stacktrace feature?

```
	public String delete(@ShellOption(help = "name of the repository to delete") @NotNull String name) {
		this.skipperClient.deleteRepository(name);
		return "Repository " + name + " deleted.";
	}
```

**Comment by ericbottard** [comment]
Depends on what you want the user experience to be, but you can let it
bubble up and Shell will catch it indeed

Le 18 sept. 2017 4:30 AM, "Mark Pollack" <notifications@github.com> a
écrit :

**Comment by sabbyanandan** [comment]
Stale issue; closing it.
