### ISSUE TITLE
Implement dynamic command availability

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-skipper#86]
Based on skipper client being set or not in most cases, the best approach may be to have a `@ShellCommandAvailability("*")` (the default) in a base class.

See https://docs.spring.io/spring-shell/docs/2.0.0.BUILD-SNAPSHOT/reference/htmlsingle/#dynamic-command-availability

**Comment by sabbyanandan** [comment]
The project has evolved significantly since when this issue was created - closing it as invalid.
