### ISSUE TITLE
Package List and Package search returns different results

### ISSUE THREAD

**Issue by johhuynh-clgx** [spring-cloud/spring-cloud-skipper#935]
Hi all, 

I am encountering the following issue of `package list` and `package search` returning different values. Please see below:

![image](https://user-images.githubusercontent.com/55721641/73225077-445e2180-4120-11ea-88cd-0c5080c216dd.png)

This is on Skipper 2.2.1.

Please let me know what other details I can provide.

**Comment by ilayaperumalg** [comment]
Hi @johhuynh-clgx, Both the `package search` and `package list` commands [use the same key in the shell method ](https://github.com/spring-cloud/spring-cloud-skipper/blob/v2.2.1.RELEASE/spring-cloud-skipper-shell-commands/src/main/java/org/springframework/cloud/skipper/shell/command/PackageCommands.java#L72)and expected to return the same result. In fact, the name `search` was meant to be an alias for `list` when using the wild card name to search when listing the packages.

Given this, I find it odd to see what you posted above.

**Comment by ilayaperumalg** [comment]
Could you confirm if this happens consistently and also share anything from the log which can help understand this better? Thanks!

**Comment by ilayaperumalg** [comment]
Closing it for now as non-issue. Please feel free to re-open if you consistently see this and have more information.
