### ISSUE TITLE
RedBlack deployment intentionally failing health check app is treated as healthy.

### ISSUE THREAD

**Issue by AbaevTM** [spring-cloud/spring-cloud-skipper#966]
Originally posted this at SO : https://stackoverflow.com/questions/63055782/spring-cloud-data-flow-treats-intentionally-failing-health-check-app-as-healthy

I use 
 - helm chart https://hub.helm.sh/charts/stable/spring-cloud-data-flow/2.7.1 
- k8s version - 1.16 (AWS EKS eks.1)
- external rabbit and postgres are used - the rest of config is default from vanilla SCDF starter articles.  

One of scenarios that I check is how SCDF handles *failures of apps*. 

One of app's versions on purpose fails health check constantly returning 503 and status DOWN. App is spring boot app. 

When stream is updated and broken version of the app is used _previous version is killed right after update_. Check section **_"How statuses look"_** it contains description of how status of pods in k8s and app and stream in SCDF looks like.

Observed behavior doesn't align with what is written in doc on "red\black" deployment strategy of Skipper.

https://docs.spring.io/spring-cloud-dataflow/docs/2.5.1.RELEASE/reference/htmlsingle/#_skipper_s_upgrade_strategy

>Skipper has a simple 'red/black' upgrade strategy. It deploys the new version of the applications, using as many instances as the currently running version, and checks the /health endpoint of the application. If the health of the new application is good, then the previous application is undeployed. If the health of the new application is bad, then all new applications are undeployed and the upgrade is considered to be not successful.

What's wrong
----------------------------

My expectation is that Skipper should preserve existing version of the app until it's sure that new version is healthy. And now it looks like it kills healthy version and deploys broken one leaving it spinning in crash loop.

Steps to reproduce the issue
----------------------------

 - stream called **my-pipeline** is deployed (v48)
 - one of app's called **my-app** is deployed with v48
 - update stream and change version for **my-app** to broken v49
 - **my-app-v48** is killed
- **my-app-v49** is started but running in crash loop constantly failing health checks and trying to restart

I checked Skipper' logs and can see following lines:

        2020-07-23 12:32:27.785  INFO 1 --- [eTaskExecutor-4] o.s.c.s.server.deployer.ReleaseAnalyzer  : 
        Existing Package and Upgrade package both have no top level templates
        2020-07-23 12:32:27.786  INFO 1 --- [eTaskExecutor-4] o.s.c.s.server.deployer.ReleaseAnalyzer  : 
        Differences detected between existing and replacing application manifests.Upgrading applications 
        = [my-app]
        2020-07-23 12:32:27.944  INFO 1 --- [eTaskExecutor-4] o.s.c.s.s.d.s.HandleHealthCheckStep      : 
        Release my-pipeline-v49 has been DEPLOYED
        2020-07-23 12:32:27.944  INFO 1 --- [eTaskExecutor-4] o.s.c.s.s.d.s.HandleHealthCheckStep      : 
        Apps in release my-pipeline-v49 are healthy.
        2020-07-23 12:32:27.954  INFO 1 --- [eTaskExecutor-4] o.s.c.s.s.d.s.HandleHealthCheckStep      : 
        Deleting changed applications from existing release my-pipeline-v48 

Looks like [HandleHealthCheckStep#handleHealthCheck][1] is called with *healthy* set to true. I guess it happens due to *"deploying"* status treated as *healthy*.

How statuses look
----------------------------

1 ) **Liveness**  is at **/actuator/health** which _fails_, **readiness** is at **/actuator/info** which is _ok_. 

**k8s status**

- pod's status is : "0/1     Running"
- after delay of readiness probe it goes to "1/1     Running".
- after failing liveness probes pod is restarted and goes back to "0/1 Running" with increased restarts count. 

**scdf status**

- app's status is *"deploying"* the same for the stream. 
- after delay for readiness it goes to *"deployed"* and the same for stream.

after 3 first restarts:
- app's status is *"failed"*, stream it's *"partial"*.
- after delay for readiness it goes to *"deployed"* and the same for stream.

2 ) Also just tried with setting both **liveness** and **rediness** both to _failing_ **actuator/health**. 

**k8s status**

- pod's status is : "0/1     Running"
- after failing liveness probes pod is restarted and goes back to "0/1 Running" with increased restarts count. 

**scdf status**

- app's status is *"deploying"* the same for the stream.

after 3 first restarts:
- app's status is *"failed"*, stream it's *"partial"*.

**_However in both scenarios existing version of app is killed right after stream's upgrade._**

  [1]: https://github.com/spring-cloud/spring-cloud-skipper/blob/6e1f82c8f7fd4df6c687a8aeaa4c82493e89f680/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HandleHealthCheckStep.java#L66

**Comment by jvalkeal** [comment]
Bad behaviour is in:
https://github.com/spring-cloud/spring-cloud-skipper/blob/07abfe7331f5c5cdf3cd12ea85270c22806f725d/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/DeleteStep.java#L63-L70

That itself is easy fix but just need to poke around if we simply undeploy without checking any status does it have other side effects.

**Comment by jvalkeal** [comment]
Ups, clicked a wrong button.

**Comment by jvalkeal** [comment]
This might also be a good time to check logic in:

https://github.com/spring-cloud/spring-cloud-skipper/blob/07abfe7331f5c5cdf3cd12ea85270c22806f725d/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/deployer/strategies/HealthCheckStep.java#L64-L70

as one might question should upgrade succeed if app i.e. in k8s will eventually fail. Should we have a setting how long to wait app to be healthy?

**Comment by AbaevTM** [comment]
@jvalkeal , do you think the issue described in https://github.com/spring-cloud/spring-cloud-skipper/issues/964 is caused by the same thing as this one?

**Comment by AbaevTM** [comment]
anyway, keep in mind that there is also the issue with not cleared unsuccessful deployments

**Comment by jvalkeal** [comment]
I think you're right, while they are slightly connected should probably handle separately. I'll re-open that.

**Comment by jvalkeal** [comment]
Just a little update on this. While this and other linked issues were relatively minor things, fixes caused some other cascading issues and work has been ongoing in a whole stack(not just skipper) to provide better functionality and testing support for these cases where things go south.

While I'm now locally on my branch able to delete/undeploy and all things what you'd expect to see, UI/shell still shows info about failed state as it's a latest release state. Still thinking how we show it to a user that update failed and it was reverted to a previous deployed state without changes.
