### ISSUE TITLE
Unable to call to stream Deployment History API

### ISSUE THREAD

**Issue by shalomyasap** [spring-cloud/spring-cloud-skipper#986]
Hello everyone, 

We are using spring data-flow version 2.7.1 and skipper 2.6.1 at cloud foundry environment.
We enabled Authentication and authorization (configuring security.authorization.provider-role-mappings.uaa and security.oauth) 

I’m trying to invoke the stream history (<data-flow>/streams/deployments/history/<stream-name>/) but I’m getting error response, 500 error code, with message body " 403 Forbidden: [no body] "

Other API works fine, such upgrade (<data-flow>/streams/deployments/update/<stream-name>) or validation (/runtime/streams/<stream-name> )

 I disabled the authorization as well, i.e. setting map-oauth-scopes to false, but still getting 403. We found out the issue might be related to the skipper server since we got the following error at the skipper: 
"GET /api/releases/search/findByNameIgnoreCaseContainingOrderByNameAscVersionDesc?name=demo-stream HTTP/1.1" 403

 Is there any special configuration for history API?

**Comment by jvalkeal** [comment]
Thx reporting this as I think it's a misconfig for permitted paths.
