### ISSUE TITLE
How to run skipper server on docker with java 14

### ISSUE THREAD

**Issue by thibaud-sanchez** [spring-cloud/spring-cloud-skipper#988]
I would like to run java14 applications using skipper but it seems that the docker image : https://hub.docker.com/layers/springcloud/spring-cloud-skipper-server is running with Java 11.
Is there any way to get the original docker file and change it to java 14 ??

**Comment by jvalkeal** [comment]
With #1010 we've added jdk16 which gives `springcloud/spring-cloud-skipper-server:2.8.0-SNAPSHOT-jdk16`. We can look if we could enable that for older branches as well.
